# CLK
set_property PACKAGE_PIN W5 [get_ports {CLK}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {CLK}]

# Buttons
set_property PACKAGE_PIN T18 [get_ports {BTN_U}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {BTN_U}]
set_property PACKAGE_PIN U17 [get_ports {BTN_D}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {BTN_D}]
set_property PACKAGE_PIN W19 [get_ports {BTN_L}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {BTN_L}]
#set_property PACKAGE_PIN U18 [get_ports {PAUSE}] 
#    set_property IOSTANDARD LVCMOS33 [get_ports {PAUSE}]
set_property PACKAGE_PIN T17 [get_ports {BTN_R}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {BTN_R}]

# Slide switchs
set_property PACKAGE_PIN V17 [get_ports {PAUSE}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {PAUSE}]
#set_property PACKAGE_PIN V16 [get_ports {SLIDE_SWITCH_IN[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[1]}]
#set_property PACKAGE_PIN W16 [get_ports {SLIDE_SWITCH_IN[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[2]}]
#set_property PACKAGE_PIN W17 [get_ports {SLIDE_SWITCH_IN[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[3]}]
#set_property PACKAGE_PIN W15 [get_ports {SLIDE_SWITCH_IN[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[4]}]
#set_property PACKAGE_PIN V15 [get_ports {SLIDE_SWITCH_IN[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[5]}]
#set_property PACKAGE_PIN W14 [get_ports {SLIDE_SWITCH_IN[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[6]}]
#set_property PACKAGE_PIN W13 [get_ports {SLIDE_SWITCH_IN[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[7]}]
#set_property PACKAGE_PIN V2 [get_ports {SLIDE_SWITCH_IN[8]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[8]}]
#set_property PACKAGE_PIN T3 [get_ports {SLIDE_SWITCH_IN[9]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[9]}]
#set_property PACKAGE_PIN T2 [get_ports {SLIDE_SWITCH_IN[10]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[10]}]
#set_property PACKAGE_PIN R3 [get_ports {SLIDE_SWITCH_IN[11]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[11]}]
#set_property PACKAGE_PIN W2 [get_ports {SLIDE_SWITCH_IN[12]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[12]}]
#set_property PACKAGE_PIN U1 [get_ports {SLIDE_SWITCH_IN[13]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {SLIDE_SWITCH_IN[13]}]
set_property PACKAGE_PIN T1 [get_ports {GAMEMODE}]
    set_property IOSTANDARD LVCMOS33 [get_ports {GAMEMODE}]
set_property PACKAGE_PIN R2 [get_ports {RESET}]
    set_property IOSTANDARD LVCMOS33 [get_ports {RESET}]
    
# 7 SEGMENT
set_property PACKAGE_PIN W7 [get_ports {HEX_OUT[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[0]}]
set_property PACKAGE_PIN W6 [get_ports {HEX_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[1]}]
set_property PACKAGE_PIN U8 [get_ports {HEX_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[2]}]
set_property PACKAGE_PIN V8 [get_ports {HEX_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[3]}]
set_property PACKAGE_PIN U5 [get_ports {HEX_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[4]}]
set_property PACKAGE_PIN V5 [get_ports {HEX_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[5]}]
set_property PACKAGE_PIN U7 [get_ports {HEX_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[6]}]
set_property PACKAGE_PIN V7 [get_ports {HEX_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HEX_OUT[7]}]
    
set_property PACKAGE_PIN U2 [get_ports {SEG_SELECT_OUT[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[0]}]
set_property PACKAGE_PIN U4 [get_ports {SEG_SELECT_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[1]}]
set_property PACKAGE_PIN V4 [get_ports {SEG_SELECT_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[2]}]
set_property PACKAGE_PIN W4 [get_ports {SEG_SELECT_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {SEG_SELECT_OUT[3]}]
    
# HS & VS
set_property PACKAGE_PIN P19 [get_ports {HS}]
    set_property IOSTANDARD LVCMOS33 [get_ports {HS}]
set_property PACKAGE_PIN R19 [get_ports {VS}]
    set_property IOSTANDARD LVCMOS33 [get_ports {VS}]
    
# Colour out
set_property PACKAGE_PIN G19 [get_ports {COLOUR_OUT[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[0]}]
set_property PACKAGE_PIN H19 [get_ports {COLOUR_OUT[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[1]}]
set_property PACKAGE_PIN J19 [get_ports {COLOUR_OUT[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[2]}]
set_property PACKAGE_PIN N19 [get_ports {COLOUR_OUT[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[3]}]
set_property PACKAGE_PIN J17 [get_ports {COLOUR_OUT[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[4]}]
set_property PACKAGE_PIN H17 [get_ports {COLOUR_OUT[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[5]}]
set_property PACKAGE_PIN G17 [get_ports {COLOUR_OUT[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[6]}]
set_property PACKAGE_PIN D17 [get_ports {COLOUR_OUT[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[7]}]
set_property PACKAGE_PIN N18 [get_ports {COLOUR_OUT[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[8]}]
set_property PACKAGE_PIN L18 [get_ports {COLOUR_OUT[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[9]}]
set_property PACKAGE_PIN K18 [get_ports {COLOUR_OUT[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[10]}]
set_property PACKAGE_PIN J18 [get_ports {COLOUR_OUT[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {COLOUR_OUT[11]}]